INCIDENTS = {
    "cpu_storm": {
        "name": "CPU Storm",
        "description": "A runaway process spikes CPU and latency.",
        "signature": "cpu>90 latency>800",
        "symptoms": [
            "cpu_usage=94%",
            "p99_latency=920ms",
            "error_rate=1.8%",
        ],
        "root_cause": "Unbounded background job spawning workers.",
        "fix": "Throttle worker pool and enable backpressure.",
        "patch": "Set WORKER_POOL=8 and enable job queue backpressure.",
        "metrics_before": {"cpu": 94, "p99_latency_ms": 920, "error_rate": 1.8},
        "metrics_after": {"cpu": 62, "p99_latency_ms": 280, "error_rate": 0.2},
    },
    "deploy_regression": {
        "name": "Deploy Regression",
        "description": "A new deploy causes 5xx spike.",
        "signature": "5xx>12%",
        "symptoms": [
            "5xx_rate=14.2%",
            "p95_latency=740ms",
            "canary_errors=high",
        ],
        "root_cause": "Config flag flipped breaking request validation.",
        "fix": "Rollback flag and restore schema validation defaults.",
        "patch": "Set VALIDATION_STRICT=false; redeploy.",
        "metrics_before": {"p95_latency_ms": 740, "error_5xx_rate": 14.2},
        "metrics_after": {"p95_latency_ms": 210, "error_5xx_rate": 0.6},
    },
    "disk_pressure": {
        "name": "Disk Pressure",
        "description": "Logs fill disk causing IO stalls.",
        "signature": "disk>92 io_wait>20",
        "symptoms": [
            "disk_usage=95%",
            "io_wait=24%",
            "queue_depth=high",
        ],
        "root_cause": "Debug logging left enabled on hot path.",
        "fix": "Rotate logs and reduce verbosity.",
        "patch": "Disable DEBUG_LOGS and run logrotate.",
        "metrics_before": {"disk_usage": 95, "io_wait": 24},
        "metrics_after": {"disk_usage": 68, "io_wait": 5},
    },
}
